export const CREATE_PROJECT = 'CREATE_PROJECT'
export const CREATE_GOAL = 'CREATE_GOAL'

//Projects
export const GET_PROJECTS_LIST = 'GET_PROJECTS_LIST'

// Tasks
export const ADD_TASK_FETCHING = 'ADD_TASK_FETCHING'
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS'

export const REMOVE_TASK_BY_ID_FETCHING = 'REMOVE_TASK_BY_ID_FETCHING'
export const REMOVE_TASK_BY_ID_SUCCESS = 'REMOVE_TASK_BY_ID_SUCCESS'

export const UPDATE_TASK_BY_ID_FETCHING = 'UPDATE_TASK_BY_ID_FETCHING'
export const UPDATE_TASK_BY_ID_SUCCESS = 'UPDATE_TASK_BY_ID_SUCCESS'

export const UPDATE_STATUS_TASK_BY_ID_FETCHING = 'UPDATE_STATUS_TASK_BY_ID_FETCHING'
export const UPDATE_STATUS_TASK_BY_ID_SUCCESS = 'UPDATE_STATUS_TASK_BY_ID_SUCCESS'

export const GET_TASKS_FETCHING = 'GET_TASKS_FETCHING'
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS'

//Auth
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'

export const FETCH = 'FETCH'